//auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOAD = 'USER_LOAD';
export const SET_AUTHLOADING = 'SET_AUTHLOADING';

//provide
export const GETMYPROVIDE = 'GETMYPROVIDE';
export const GETMYPROVIDE_FAIL = 'GETMYPROVIDE_FAIL';
export const CLEAR_PROVIDE = 'CLEAR_PROVIDE';
export const GETPROVIDES = 'GETPROVIDES';
export const GETPROVIDES_FAIL = 'GETPROVIDES_FAIL';

//requests
export const GETREQUESTS = 'GETREQUESTS';
export const REQUESTS_FAIL = 'REQUESTS_FAIL';
export const CLEAR_REQUESTS = 'CLEAR_REQUESTS';
export const POSTREQUEST = 'POSTREQUEST';
export const POSTREQUEST_FAIL = 'POSTREQUEST_FAIL';
export const UPDATEREQUEST = 'UPDATEREQUEST';
export const UPDATEREQUEST_FAIL = 'UPDATEREQUEST_FAIL';

//userUtil
export const GETLANGUAGES = 'GETLANGUAGES';
export const GETLANGUAGESFAIL = 'GETLANGUAGESFAIL';
export const GETSERVICETYPES = 'GETSERVICETYPE';
export const GETSERVICETYPESFAIL = 'GETSERVICETYPEFAIL';
export const GETROLES = 'GETROLES';
export const GETROLESFAIL = 'GETROLESFAIL';
export const CLEARUSERUTIL = 'CLEARUSERUTIL';

//comment
export const GETCOMMENTS = 'GETCOMMENTS';
export const GETCOMMENTS_FAIL = 'GETCOMMENTS_FAIL';
export const GETCOMMENT = 'GETCOMMENT';
export const GETCOMMENT_FAIL = 'GETCOMMENT_FAIL';
export const SET_COMMENT = 'SET_COMMENT';
export const POSTCOMMENT = 'POSTCOMMENT';
export const POSTCOMMENT_FAIL = 'POSTCOMMENT_FAIL';

//admin
export const ADMINGETLANGUAGES = 'ADMINGETLANGUAGES';
export const ADMINGETLANGUAGES_FAIL = 'ADMINGETLANGUAGES_FAIL';
export const ADMINGETSERVICETYPES = 'ADMINGETSERVICETYPES';
export const ADMINGETSERVICETYPES_FAIL = 'ADMINGETSERVICETYPES_FAIL';
export const ADMINGETROLES = 'ADMINGETROLES';
export const ADMINGETROLES_FAIL = 'ADMINGETROLES_FAIL';
export const ADMINGETUSERS = 'ADMINGETUSERS';
export const ADMINGETUSERS_FAIL = 'ADMINGETUSERS_FAIL';
export const CLEARADMIN = 'CLEARADMIN';
export const ADMINPOSTLANGUAGE = 'ADMINPOSTLANGUAGE';
export const ADMINPOSTLANGUAGE_FAIL = 'ADMINPOSTLANGUAGE_FAIL';
export const ADMINPOSTSERVICETYPE = 'ADMINPOSTSERVICETYPE';
export const ADMINPOSTSERVICETYPE_FAIL = 'ADMINPOSTSERVICETYPE_FAIL';
export const ADMINPOSTROLE = 'ADMINPOSTROLE';
export const ADMINPOSTROLE_FAIL = 'ADMINPOSTROLE_FAIL';

//alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
